// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createAuditLogEvent = `-- name: CreateAuditLogEvent :one
INSERT INTO audit_log_events (
    id,
    event_type,
    actor_principal_type,
    actor_principal_id,
    actor_display,
    target_type,
    target_id,
    project_id,
    ip_address,
    user_agent,
    metadata_json,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    event_type,
    actor_principal_type,
    actor_principal_id,
    actor_display,
    target_type,
    target_id,
    project_id,
    ip_address,
    user_agent,
    metadata_json,
    created_at
`

type CreateAuditLogEventParams struct {
	ID                 string
	EventType          string
	ActorPrincipalType sql.NullString
	ActorPrincipalID   sql.NullString
	ActorDisplay       sql.NullString
	TargetType         sql.NullString
	TargetID           sql.NullString
	ProjectID          sql.NullString
	IpAddress          sql.NullString
	UserAgent          sql.NullString
	MetadataJson       string
	CreatedAt          time.Time
}

func (q *Queries) CreateAuditLogEvent(ctx context.Context, arg CreateAuditLogEventParams) (AuditLogEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditLogEvent,
		arg.ID,
		arg.EventType,
		arg.ActorPrincipalType,
		arg.ActorPrincipalID,
		arg.ActorDisplay,
		arg.TargetType,
		arg.TargetID,
		arg.ProjectID,
		arg.IpAddress,
		arg.UserAgent,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i AuditLogEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorPrincipalType,
		&i.ActorPrincipalID,
		&i.ActorDisplay,
		&i.TargetType,
		&i.TargetID,
		&i.ProjectID,
		&i.IpAddress,
		&i.UserAgent,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventTypes = `-- name: ListAuditEventTypes :many
SELECT DISTINCT event_type
FROM audit_log_events
ORDER BY event_type
`

func (q *Queries) ListAuditEventTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogEvents = `-- name: ListAuditLogEvents :many
SELECT
    id,
    event_type,
    actor_principal_type,
    actor_principal_id,
    actor_display,
    target_type,
    target_id,
    project_id,
    ip_address,
    user_agent,
    metadata_json,
    created_at
FROM audit_log_events
WHERE
    (? IS NULL OR event_type = ?)
    AND (? IS NULL OR project_id = ?)
    AND (? IS NULL OR target_type = ?)
    AND (? IS NULL OR target_id = ?)
    AND (? IS NULL OR created_at >= ?)
    AND (? IS NULL OR created_at <= ?)
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditLogEventsParams struct {
	Column1     interface{}
	EventType   string
	Column3     interface{}
	ProjectID   sql.NullString
	Column5     interface{}
	TargetType  sql.NullString
	Column7     interface{}
	TargetID    sql.NullString
	Column9     interface{}
	CreatedAt   time.Time
	Column11    interface{}
	CreatedAt_2 time.Time
	Limit       int64
}

func (q *Queries) ListAuditLogEvents(ctx context.Context, arg ListAuditLogEventsParams) ([]AuditLogEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogEvents,
		arg.Column1,
		arg.EventType,
		arg.Column3,
		arg.ProjectID,
		arg.Column5,
		arg.TargetType,
		arg.Column7,
		arg.TargetID,
		arg.Column9,
		arg.CreatedAt,
		arg.Column11,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLogEvent
	for rows.Next() {
		var i AuditLogEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorPrincipalType,
			&i.ActorPrincipalID,
			&i.ActorDisplay,
			&i.TargetType,
			&i.TargetID,
			&i.ProjectID,
			&i.IpAddress,
			&i.UserAgent,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
