// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createFindingComment = `-- name: CreateFindingComment :one
INSERT INTO finding_comments (
    id,
    finding_id,
    project_id,
    author_principal_type,
    author_principal_id,
    body,
    is_system,
    status_from,
    status_to,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id,
    finding_id,
    project_id,
    author_principal_type,
    author_principal_id,
    body,
    is_system,
    status_from,
    status_to,
    created_at,
    updated_at
`

type CreateFindingCommentParams struct {
	ID                  string
	FindingID           string
	ProjectID           string
	AuthorPrincipalType string
	AuthorPrincipalID   string
	Body                string
	IsSystem            bool
	StatusFrom          sql.NullString
	StatusTo            sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateFindingComment(ctx context.Context, arg CreateFindingCommentParams) (FindingComment, error) {
	row := q.db.QueryRowContext(ctx, createFindingComment,
		arg.ID,
		arg.FindingID,
		arg.ProjectID,
		arg.AuthorPrincipalType,
		arg.AuthorPrincipalID,
		arg.Body,
		arg.IsSystem,
		arg.StatusFrom,
		arg.StatusTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FindingComment
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ProjectID,
		&i.AuthorPrincipalType,
		&i.AuthorPrincipalID,
		&i.Body,
		&i.IsSystem,
		&i.StatusFrom,
		&i.StatusTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFindingStatusChangeRequest = `-- name: CreateFindingStatusChangeRequest :one
INSERT INTO finding_status_change_requests (
    id,
    finding_id,
    project_id,
    requester_principal_type,
    requester_principal_id,
    reviewer_principal_type,
    reviewer_principal_id,
    from_status,
    to_status,
    state,
    comment,
    decision_comment,
    decided_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING
    id,
    finding_id,
    project_id,
    requester_principal_type,
    requester_principal_id,
    reviewer_principal_type,
    reviewer_principal_id,
    from_status,
    to_status,
    state,
    comment,
    decision_comment,
    decided_at,
    created_at,
    updated_at
`

type CreateFindingStatusChangeRequestParams struct {
	ID                     string
	FindingID              string
	ProjectID              string
	RequesterPrincipalType string
	RequesterPrincipalID   string
	ReviewerPrincipalType  sql.NullString
	ReviewerPrincipalID    sql.NullString
	FromStatus             string
	ToStatus               string
	State                  string
	Comment                sql.NullString
	DecisionComment        sql.NullString
	DecidedAt              sql.NullTime
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateFindingStatusChangeRequest(ctx context.Context, arg CreateFindingStatusChangeRequestParams) (FindingStatusChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, createFindingStatusChangeRequest,
		arg.ID,
		arg.FindingID,
		arg.ProjectID,
		arg.RequesterPrincipalType,
		arg.RequesterPrincipalID,
		arg.ReviewerPrincipalType,
		arg.ReviewerPrincipalID,
		arg.FromStatus,
		arg.ToStatus,
		arg.State,
		arg.Comment,
		arg.DecisionComment,
		arg.DecidedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FindingStatusChangeRequest
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ProjectID,
		&i.RequesterPrincipalType,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalType,
		&i.ReviewerPrincipalID,
		&i.FromStatus,
		&i.ToStatus,
		&i.State,
		&i.Comment,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingRow = `-- name: GetFindingRow :one
SELECT
    raw_finding_instances.id AS finding_id,
    raw_finding_instances.project_id,
    projects.name AS project_name,
    raw_finding_instances.scan_target_id,
    asset_nodes.name AS scan_target_name,
    asset_nodes.path AS scan_target_path,
    asset_nodes.target_ref AS scan_target_ref,
    raw_finding_instances.scanner_kind,
    scans.report_kind,
    raw_finding_instances.scanner_finding_id,
    raw_finding_instances.dedupe_key,
    raw_finding_instances.identifiers_json,
    raw_finding_instances.primary_identifier,
    raw_finding_instances.severity,
    raw_finding_instances.cvss_json,
    raw_finding_instances.package_name,
    raw_finding_instances.package_version,
    raw_finding_instances.fixed_version,
    raw_finding_instances.artifact_name,
    raw_finding_instances.artifact_type,
    raw_finding_instances.artifact_path,
    raw_finding_instances.first_seen_at,
    raw_finding_instances.last_seen_at,
    raw_finding_instances.present_in_latest_scan,
    raw_finding_instances.status,
    raw_finding_instances.references_json,
    raw_finding_instances.source_json,
    projects.sla_tracking_enabled,
    projects.sla_reporting_enabled,
    projects.grace_period_enabled,
    projects.grace_period_percent,
    projects.critical_sla_days,
    projects.high_sla_days,
    projects.medium_sla_days,
    projects.low_sla_days,
    projects.unknown_sla_days,
    asset_nodes.sla_tracking_enabled AS asset_sla_tracking_enabled,
    asset_nodes.sla_reporting_enabled AS asset_sla_reporting_enabled,
    asset_nodes.grace_period_enabled AS asset_grace_period_enabled,
    asset_nodes.grace_period_percent AS asset_grace_period_percent,
    project_vulnerability_groups.id AS group_id,
    project_vulnerability_groups.primary_identifier AS group_primary_identifier,
    project_vulnerability_groups.additional_identifiers_json AS group_additional_identifiers_json,
    project_vulnerability_groups.first_detected_at AS group_first_detected_at,
    project_vulnerability_groups.status AS group_status
FROM raw_finding_instances
JOIN scans ON scans.id = raw_finding_instances.scan_id
JOIN projects ON projects.id = raw_finding_instances.project_id
JOIN asset_nodes ON asset_nodes.id = raw_finding_instances.scan_target_id
LEFT JOIN project_vulnerability_groups ON
    project_vulnerability_groups.project_id = raw_finding_instances.project_id
    AND project_vulnerability_groups.dedupe_key = raw_finding_instances.primary_identifier
WHERE raw_finding_instances.id = $1
`

type GetFindingRowRow struct {
	FindingID                      string
	ProjectID                      string
	ProjectName                    string
	ScanTargetID                   string
	ScanTargetName                 string
	ScanTargetPath                 string
	ScanTargetRef                  sql.NullString
	ScannerKind                    string
	ReportKind                     string
	ScannerFindingID               string
	DedupeKey                      string
	IdentifiersJson                string
	PrimaryIdentifier              string
	Severity                       string
	CvssJson                       string
	PackageName                    sql.NullString
	PackageVersion                 sql.NullString
	FixedVersion                   sql.NullString
	ArtifactName                   sql.NullString
	ArtifactType                   sql.NullString
	ArtifactPath                   sql.NullString
	FirstSeenAt                    time.Time
	LastSeenAt                     time.Time
	PresentInLatestScan            bool
	Status                         string
	ReferencesJson                 string
	SourceJson                     string
	SlaTrackingEnabled             bool
	SlaReportingEnabled            bool
	GracePeriodEnabled             bool
	GracePeriodPercent             int64
	CriticalSlaDays                int64
	HighSlaDays                    int64
	MediumSlaDays                  int64
	LowSlaDays                     int64
	UnknownSlaDays                 int64
	AssetSlaTrackingEnabled        sql.NullBool
	AssetSlaReportingEnabled       sql.NullBool
	AssetGracePeriodEnabled        sql.NullBool
	AssetGracePeriodPercent        sql.NullInt64
	GroupID                        sql.NullString
	GroupPrimaryIdentifier         sql.NullString
	GroupAdditionalIdentifiersJson sql.NullString
	GroupFirstDetectedAt           sql.NullTime
	GroupStatus                    sql.NullString
}

func (q *Queries) GetFindingRow(ctx context.Context, id string) (GetFindingRowRow, error) {
	row := q.db.QueryRowContext(ctx, getFindingRow, id)
	var i GetFindingRowRow
	err := row.Scan(
		&i.FindingID,
		&i.ProjectID,
		&i.ProjectName,
		&i.ScanTargetID,
		&i.ScanTargetName,
		&i.ScanTargetPath,
		&i.ScanTargetRef,
		&i.ScannerKind,
		&i.ReportKind,
		&i.ScannerFindingID,
		&i.DedupeKey,
		&i.IdentifiersJson,
		&i.PrimaryIdentifier,
		&i.Severity,
		&i.CvssJson,
		&i.PackageName,
		&i.PackageVersion,
		&i.FixedVersion,
		&i.ArtifactName,
		&i.ArtifactType,
		&i.ArtifactPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PresentInLatestScan,
		&i.Status,
		&i.ReferencesJson,
		&i.SourceJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.AssetSlaTrackingEnabled,
		&i.AssetSlaReportingEnabled,
		&i.AssetGracePeriodEnabled,
		&i.AssetGracePeriodPercent,
		&i.GroupID,
		&i.GroupPrimaryIdentifier,
		&i.GroupAdditionalIdentifiersJson,
		&i.GroupFirstDetectedAt,
		&i.GroupStatus,
	)
	return i, err
}

const getFindingStatusChangeRequest = `-- name: GetFindingStatusChangeRequest :one
SELECT
    id,
    finding_id,
    project_id,
    requester_principal_type,
    requester_principal_id,
    reviewer_principal_type,
    reviewer_principal_id,
    from_status,
    to_status,
    state,
    comment,
    decision_comment,
    decided_at,
    created_at,
    updated_at
FROM finding_status_change_requests
WHERE id = $1 AND finding_id = $2
`

type GetFindingStatusChangeRequestParams struct {
	ID        string
	FindingID string
}

func (q *Queries) GetFindingStatusChangeRequest(ctx context.Context, arg GetFindingStatusChangeRequestParams) (FindingStatusChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getFindingStatusChangeRequest, arg.ID, arg.FindingID)
	var i FindingStatusChangeRequest
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ProjectID,
		&i.RequesterPrincipalType,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalType,
		&i.ReviewerPrincipalID,
		&i.FromStatus,
		&i.ToStatus,
		&i.State,
		&i.Comment,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindingComments = `-- name: ListFindingComments :many
SELECT
    finding_comments.id,
    finding_comments.finding_id,
    finding_comments.project_id,
    finding_comments.author_principal_type,
    finding_comments.author_principal_id,
    users.display_name AS user_display,
    machine_credentials.name AS machine_display,
    finding_comments.body,
    finding_comments.is_system,
    finding_comments.status_from,
    finding_comments.status_to,
    finding_comments.created_at,
    finding_comments.updated_at
FROM finding_comments
LEFT JOIN users ON users.id = finding_comments.author_principal_id
    AND finding_comments.author_principal_type = 'user'
LEFT JOIN machine_credentials ON machine_credentials.id = finding_comments.author_principal_id
    AND finding_comments.author_principal_type = 'machine'
WHERE finding_comments.finding_id = $1
ORDER BY finding_comments.created_at, finding_comments.id
`

type ListFindingCommentsRow struct {
	ID                  string
	FindingID           string
	ProjectID           string
	AuthorPrincipalType string
	AuthorPrincipalID   string
	UserDisplay         sql.NullString
	MachineDisplay      sql.NullString
	Body                string
	IsSystem            bool
	StatusFrom          sql.NullString
	StatusTo            sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ListFindingComments(ctx context.Context, findingID string) ([]ListFindingCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingComments, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingCommentsRow
	for rows.Next() {
		var i ListFindingCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ProjectID,
			&i.AuthorPrincipalType,
			&i.AuthorPrincipalID,
			&i.UserDisplay,
			&i.MachineDisplay,
			&i.Body,
			&i.IsSystem,
			&i.StatusFrom,
			&i.StatusTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingRows = `-- name: ListFindingRows :many
SELECT
    raw_finding_instances.id AS finding_id,
    raw_finding_instances.project_id,
    projects.name AS project_name,
    raw_finding_instances.scan_target_id,
    asset_nodes.name AS scan_target_name,
    asset_nodes.path AS scan_target_path,
    asset_nodes.target_ref AS scan_target_ref,
    raw_finding_instances.scanner_kind,
    scans.report_kind,
    raw_finding_instances.scanner_finding_id,
    raw_finding_instances.dedupe_key,
    raw_finding_instances.identifiers_json,
    raw_finding_instances.primary_identifier,
    raw_finding_instances.severity,
    raw_finding_instances.cvss_json,
    raw_finding_instances.package_name,
    raw_finding_instances.package_version,
    raw_finding_instances.fixed_version,
    raw_finding_instances.artifact_name,
    raw_finding_instances.artifact_type,
    raw_finding_instances.artifact_path,
    raw_finding_instances.first_seen_at,
    raw_finding_instances.last_seen_at,
    raw_finding_instances.present_in_latest_scan,
    raw_finding_instances.status,
    raw_finding_instances.references_json,
    raw_finding_instances.source_json,
    projects.sla_tracking_enabled,
    projects.sla_reporting_enabled,
    projects.grace_period_enabled,
    projects.grace_period_percent,
    projects.critical_sla_days,
    projects.high_sla_days,
    projects.medium_sla_days,
    projects.low_sla_days,
    projects.unknown_sla_days,
    asset_nodes.sla_tracking_enabled AS asset_sla_tracking_enabled,
    asset_nodes.sla_reporting_enabled AS asset_sla_reporting_enabled,
    asset_nodes.grace_period_enabled AS asset_grace_period_enabled,
    asset_nodes.grace_period_percent AS asset_grace_period_percent,
    project_vulnerability_groups.id AS group_id,
    project_vulnerability_groups.primary_identifier AS group_primary_identifier,
    project_vulnerability_groups.additional_identifiers_json AS group_additional_identifiers_json,
    project_vulnerability_groups.first_detected_at AS group_first_detected_at,
    project_vulnerability_groups.status AS group_status
FROM raw_finding_instances
JOIN scans ON scans.id = raw_finding_instances.scan_id
JOIN projects ON projects.id = raw_finding_instances.project_id
JOIN asset_nodes ON asset_nodes.id = raw_finding_instances.scan_target_id
LEFT JOIN project_vulnerability_groups ON
    project_vulnerability_groups.project_id = raw_finding_instances.project_id
    AND project_vulnerability_groups.dedupe_key = raw_finding_instances.primary_identifier
ORDER BY raw_finding_instances.last_seen_at DESC, raw_finding_instances.primary_identifier, raw_finding_instances.id
`

type ListFindingRowsRow struct {
	FindingID                      string
	ProjectID                      string
	ProjectName                    string
	ScanTargetID                   string
	ScanTargetName                 string
	ScanTargetPath                 string
	ScanTargetRef                  sql.NullString
	ScannerKind                    string
	ReportKind                     string
	ScannerFindingID               string
	DedupeKey                      string
	IdentifiersJson                string
	PrimaryIdentifier              string
	Severity                       string
	CvssJson                       string
	PackageName                    sql.NullString
	PackageVersion                 sql.NullString
	FixedVersion                   sql.NullString
	ArtifactName                   sql.NullString
	ArtifactType                   sql.NullString
	ArtifactPath                   sql.NullString
	FirstSeenAt                    time.Time
	LastSeenAt                     time.Time
	PresentInLatestScan            bool
	Status                         string
	ReferencesJson                 string
	SourceJson                     string
	SlaTrackingEnabled             bool
	SlaReportingEnabled            bool
	GracePeriodEnabled             bool
	GracePeriodPercent             int64
	CriticalSlaDays                int64
	HighSlaDays                    int64
	MediumSlaDays                  int64
	LowSlaDays                     int64
	UnknownSlaDays                 int64
	AssetSlaTrackingEnabled        sql.NullBool
	AssetSlaReportingEnabled       sql.NullBool
	AssetGracePeriodEnabled        sql.NullBool
	AssetGracePeriodPercent        sql.NullInt64
	GroupID                        sql.NullString
	GroupPrimaryIdentifier         sql.NullString
	GroupAdditionalIdentifiersJson sql.NullString
	GroupFirstDetectedAt           sql.NullTime
	GroupStatus                    sql.NullString
}

func (q *Queries) ListFindingRows(ctx context.Context) ([]ListFindingRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingRowsRow
	for rows.Next() {
		var i ListFindingRowsRow
		if err := rows.Scan(
			&i.FindingID,
			&i.ProjectID,
			&i.ProjectName,
			&i.ScanTargetID,
			&i.ScanTargetName,
			&i.ScanTargetPath,
			&i.ScanTargetRef,
			&i.ScannerKind,
			&i.ReportKind,
			&i.ScannerFindingID,
			&i.DedupeKey,
			&i.IdentifiersJson,
			&i.PrimaryIdentifier,
			&i.Severity,
			&i.CvssJson,
			&i.PackageName,
			&i.PackageVersion,
			&i.FixedVersion,
			&i.ArtifactName,
			&i.ArtifactType,
			&i.ArtifactPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PresentInLatestScan,
			&i.Status,
			&i.ReferencesJson,
			&i.SourceJson,
			&i.SlaTrackingEnabled,
			&i.SlaReportingEnabled,
			&i.GracePeriodEnabled,
			&i.GracePeriodPercent,
			&i.CriticalSlaDays,
			&i.HighSlaDays,
			&i.MediumSlaDays,
			&i.LowSlaDays,
			&i.UnknownSlaDays,
			&i.AssetSlaTrackingEnabled,
			&i.AssetSlaReportingEnabled,
			&i.AssetGracePeriodEnabled,
			&i.AssetGracePeriodPercent,
			&i.GroupID,
			&i.GroupPrimaryIdentifier,
			&i.GroupAdditionalIdentifiersJson,
			&i.GroupFirstDetectedAt,
			&i.GroupStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingStatusChangeRequests = `-- name: ListFindingStatusChangeRequests :many
SELECT
    finding_status_change_requests.id,
    finding_status_change_requests.finding_id,
    finding_status_change_requests.project_id,
    finding_status_change_requests.requester_principal_type,
    finding_status_change_requests.requester_principal_id,
    requester_user.display_name AS requester_user_display,
    requester_machine.name AS requester_machine_display,
    finding_status_change_requests.reviewer_principal_type,
    finding_status_change_requests.reviewer_principal_id,
    reviewer_user.display_name AS reviewer_user_display,
    reviewer_machine.name AS reviewer_machine_display,
    finding_status_change_requests.from_status,
    finding_status_change_requests.to_status,
    finding_status_change_requests.state,
    finding_status_change_requests.comment,
    finding_status_change_requests.decision_comment,
    finding_status_change_requests.decided_at,
    finding_status_change_requests.created_at,
    finding_status_change_requests.updated_at
FROM finding_status_change_requests
LEFT JOIN users AS requester_user ON requester_user.id = finding_status_change_requests.requester_principal_id
    AND finding_status_change_requests.requester_principal_type = 'user'
LEFT JOIN machine_credentials AS requester_machine ON requester_machine.id = finding_status_change_requests.requester_principal_id
    AND finding_status_change_requests.requester_principal_type = 'machine'
LEFT JOIN users AS reviewer_user ON reviewer_user.id = finding_status_change_requests.reviewer_principal_id
    AND finding_status_change_requests.reviewer_principal_type = 'user'
LEFT JOIN machine_credentials AS reviewer_machine ON reviewer_machine.id = finding_status_change_requests.reviewer_principal_id
    AND finding_status_change_requests.reviewer_principal_type = 'machine'
WHERE finding_status_change_requests.finding_id = $1
ORDER BY finding_status_change_requests.created_at, finding_status_change_requests.id
`

type ListFindingStatusChangeRequestsRow struct {
	ID                      string
	FindingID               string
	ProjectID               string
	RequesterPrincipalType  string
	RequesterPrincipalID    string
	RequesterUserDisplay    sql.NullString
	RequesterMachineDisplay sql.NullString
	ReviewerPrincipalType   sql.NullString
	ReviewerPrincipalID     sql.NullString
	ReviewerUserDisplay     sql.NullString
	ReviewerMachineDisplay  sql.NullString
	FromStatus              string
	ToStatus                string
	State                   string
	Comment                 sql.NullString
	DecisionComment         sql.NullString
	DecidedAt               sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) ListFindingStatusChangeRequests(ctx context.Context, findingID string) ([]ListFindingStatusChangeRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingStatusChangeRequests, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingStatusChangeRequestsRow
	for rows.Next() {
		var i ListFindingStatusChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ProjectID,
			&i.RequesterPrincipalType,
			&i.RequesterPrincipalID,
			&i.RequesterUserDisplay,
			&i.RequesterMachineDisplay,
			&i.ReviewerPrincipalType,
			&i.ReviewerPrincipalID,
			&i.ReviewerUserDisplay,
			&i.ReviewerMachineDisplay,
			&i.FromStatus,
			&i.ToStatus,
			&i.State,
			&i.Comment,
			&i.DecisionComment,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseStatusDecisions = `-- name: ListReleaseStatusDecisions :many
SELECT
    id,
    project_id,
    release_scope_asset_id,
    release_version_asset_id,
    release_version,
    scanner_kind,
    report_kind,
    finding_identity,
    status,
    source_finding_id,
    source_comment_id,
    source_request_id,
    decided_at,
    created_at,
    updated_at
FROM finding_release_status_decisions
WHERE
    project_id = $1
    AND release_scope_asset_id = $2
    AND scanner_kind = $3
    AND report_kind = $4
    AND finding_identity = $5
`

type ListReleaseStatusDecisionsParams struct {
	ProjectID           string
	ReleaseScopeAssetID string
	ScannerKind         string
	ReportKind          string
	FindingIdentity     string
}

func (q *Queries) ListReleaseStatusDecisions(ctx context.Context, arg ListReleaseStatusDecisionsParams) ([]FindingReleaseStatusDecision, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseStatusDecisions,
		arg.ProjectID,
		arg.ReleaseScopeAssetID,
		arg.ScannerKind,
		arg.ReportKind,
		arg.FindingIdentity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindingReleaseStatusDecision
	for rows.Next() {
		var i FindingReleaseStatusDecision
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleaseScopeAssetID,
			&i.ReleaseVersionAssetID,
			&i.ReleaseVersion,
			&i.ScannerKind,
			&i.ReportKind,
			&i.FindingIdentity,
			&i.Status,
			&i.SourceFindingID,
			&i.SourceCommentID,
			&i.SourceRequestID,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFindingStatusChangeRequestDecision = `-- name: UpdateFindingStatusChangeRequestDecision :one
UPDATE finding_status_change_requests
SET
    state = $1,
    reviewer_principal_type = $2,
    reviewer_principal_id = $3,
    decision_comment = $4,
    decided_at = $5,
    updated_at = $6
WHERE id = $7
RETURNING
    id,
    finding_id,
    project_id,
    requester_principal_type,
    requester_principal_id,
    reviewer_principal_type,
    reviewer_principal_id,
    from_status,
    to_status,
    state,
    comment,
    decision_comment,
    decided_at,
    created_at,
    updated_at
`

type UpdateFindingStatusChangeRequestDecisionParams struct {
	State                 string
	ReviewerPrincipalType sql.NullString
	ReviewerPrincipalID   sql.NullString
	DecisionComment       sql.NullString
	DecidedAt             sql.NullTime
	UpdatedAt             time.Time
	ID                    string
}

func (q *Queries) UpdateFindingStatusChangeRequestDecision(ctx context.Context, arg UpdateFindingStatusChangeRequestDecisionParams) (FindingStatusChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, updateFindingStatusChangeRequestDecision,
		arg.State,
		arg.ReviewerPrincipalType,
		arg.ReviewerPrincipalID,
		arg.DecisionComment,
		arg.DecidedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i FindingStatusChangeRequest
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ProjectID,
		&i.RequesterPrincipalType,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalType,
		&i.ReviewerPrincipalID,
		&i.FromStatus,
		&i.ToStatus,
		&i.State,
		&i.Comment,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectVulnerabilityGroupStatus = `-- name: UpdateProjectVulnerabilityGroupStatus :exec
UPDATE project_vulnerability_groups
SET status = $1, updated_at = $2
WHERE project_id = $3 AND dedupe_key = $4
`

type UpdateProjectVulnerabilityGroupStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ProjectID string
	DedupeKey string
}

func (q *Queries) UpdateProjectVulnerabilityGroupStatus(ctx context.Context, arg UpdateProjectVulnerabilityGroupStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectVulnerabilityGroupStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.DedupeKey,
	)
	return err
}

const updateRawFindingStatus = `-- name: UpdateRawFindingStatus :one
UPDATE raw_finding_instances
SET status = $1, updated_at = $2
WHERE id = $3
RETURNING
    id,
    project_id,
    scan_id,
    scan_target_id,
    scanner_kind,
    scanner_finding_id,
    dedupe_key,
    identifiers_json,
    primary_identifier,
    severity,
    cvss_json,
    package_name,
    package_version,
    fixed_version,
    artifact_name,
    artifact_type,
    artifact_path,
    first_seen_at,
    last_seen_at,
    present_in_latest_scan,
    status,
    references_json,
    source_json,
    created_at,
    updated_at
`

type UpdateRawFindingStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateRawFindingStatus(ctx context.Context, arg UpdateRawFindingStatusParams) (RawFindingInstance, error) {
	row := q.db.QueryRowContext(ctx, updateRawFindingStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i RawFindingInstance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanID,
		&i.ScanTargetID,
		&i.ScannerKind,
		&i.ScannerFindingID,
		&i.DedupeKey,
		&i.IdentifiersJson,
		&i.PrimaryIdentifier,
		&i.Severity,
		&i.CvssJson,
		&i.PackageName,
		&i.PackageVersion,
		&i.FixedVersion,
		&i.ArtifactName,
		&i.ArtifactType,
		&i.ArtifactPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PresentInLatestScan,
		&i.Status,
		&i.ReferencesJson,
		&i.SourceJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFindingReleaseStatusDecision = `-- name: UpsertFindingReleaseStatusDecision :one
INSERT INTO finding_release_status_decisions (
    id,
    project_id,
    release_scope_asset_id,
    release_version_asset_id,
    release_version,
    scanner_kind,
    report_kind,
    finding_identity,
    status,
    source_finding_id,
    source_comment_id,
    source_request_id,
    decided_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (
    project_id,
    release_scope_asset_id,
    release_version_asset_id,
    scanner_kind,
    report_kind,
    finding_identity
) DO UPDATE SET
    release_version = excluded.release_version,
    status = excluded.status,
    source_finding_id = excluded.source_finding_id,
    source_comment_id = excluded.source_comment_id,
    source_request_id = excluded.source_request_id,
    decided_at = excluded.decided_at,
    updated_at = excluded.updated_at
RETURNING
    id,
    project_id,
    release_scope_asset_id,
    release_version_asset_id,
    release_version,
    scanner_kind,
    report_kind,
    finding_identity,
    status,
    source_finding_id,
    source_comment_id,
    source_request_id,
    decided_at,
    created_at,
    updated_at
`

type UpsertFindingReleaseStatusDecisionParams struct {
	ID                    string
	ProjectID             string
	ReleaseScopeAssetID   string
	ReleaseVersionAssetID string
	ReleaseVersion        string
	ScannerKind           string
	ReportKind            string
	FindingIdentity       string
	Status                string
	SourceFindingID       string
	SourceCommentID       sql.NullString
	SourceRequestID       sql.NullString
	DecidedAt             time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) UpsertFindingReleaseStatusDecision(ctx context.Context, arg UpsertFindingReleaseStatusDecisionParams) (FindingReleaseStatusDecision, error) {
	row := q.db.QueryRowContext(ctx, upsertFindingReleaseStatusDecision,
		arg.ID,
		arg.ProjectID,
		arg.ReleaseScopeAssetID,
		arg.ReleaseVersionAssetID,
		arg.ReleaseVersion,
		arg.ScannerKind,
		arg.ReportKind,
		arg.FindingIdentity,
		arg.Status,
		arg.SourceFindingID,
		arg.SourceCommentID,
		arg.SourceRequestID,
		arg.DecidedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FindingReleaseStatusDecision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseScopeAssetID,
		&i.ReleaseVersionAssetID,
		&i.ReleaseVersion,
		&i.ScannerKind,
		&i.ReportKind,
		&i.FindingIdentity,
		&i.Status,
		&i.SourceFindingID,
		&i.SourceCommentID,
		&i.SourceRequestID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
