// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getFindingRow = `-- name: GetFindingRow :one
SELECT
    raw_finding_instances.id AS finding_id,
    raw_finding_instances.project_id,
    projects.name AS project_name,
    raw_finding_instances.scan_target_id,
    asset_nodes.name AS scan_target_name,
    asset_nodes.path AS scan_target_path,
    asset_nodes.target_ref AS scan_target_ref,
    raw_finding_instances.scanner_kind,
    raw_finding_instances.scanner_finding_id,
    raw_finding_instances.dedupe_key,
    raw_finding_instances.identifiers_json,
    raw_finding_instances.primary_identifier,
    raw_finding_instances.severity,
    raw_finding_instances.cvss_json,
    raw_finding_instances.package_name,
    raw_finding_instances.package_version,
    raw_finding_instances.fixed_version,
    raw_finding_instances.artifact_name,
    raw_finding_instances.artifact_type,
    raw_finding_instances.artifact_path,
    raw_finding_instances.first_seen_at,
    raw_finding_instances.last_seen_at,
    raw_finding_instances.present_in_latest_scan,
    raw_finding_instances.status,
    raw_finding_instances.references_json,
    raw_finding_instances.source_json,
    projects.sla_tracking_enabled,
    projects.sla_reporting_enabled,
    projects.grace_period_enabled,
    projects.grace_period_percent,
    projects.critical_sla_days,
    projects.high_sla_days,
    projects.medium_sla_days,
    projects.low_sla_days,
    projects.unknown_sla_days,
    asset_nodes.sla_tracking_enabled AS asset_sla_tracking_enabled,
    asset_nodes.sla_reporting_enabled AS asset_sla_reporting_enabled,
    asset_nodes.grace_period_enabled AS asset_grace_period_enabled,
    asset_nodes.grace_period_percent AS asset_grace_period_percent,
    project_vulnerability_groups.id AS group_id,
    project_vulnerability_groups.primary_identifier AS group_primary_identifier,
    project_vulnerability_groups.additional_identifiers_json AS group_additional_identifiers_json,
    project_vulnerability_groups.first_detected_at AS group_first_detected_at,
    project_vulnerability_groups.status AS group_status
FROM raw_finding_instances
JOIN projects ON projects.id = raw_finding_instances.project_id
JOIN asset_nodes ON asset_nodes.id = raw_finding_instances.scan_target_id
LEFT JOIN project_vulnerability_groups ON
    project_vulnerability_groups.project_id = raw_finding_instances.project_id
    AND project_vulnerability_groups.dedupe_key = raw_finding_instances.primary_identifier
WHERE raw_finding_instances.id = ?
`

type GetFindingRowRow struct {
	FindingID                      string
	ProjectID                      string
	ProjectName                    string
	ScanTargetID                   string
	ScanTargetName                 string
	ScanTargetPath                 string
	ScanTargetRef                  sql.NullString
	ScannerKind                    string
	ScannerFindingID               string
	DedupeKey                      string
	IdentifiersJson                string
	PrimaryIdentifier              string
	Severity                       string
	CvssJson                       string
	PackageName                    sql.NullString
	PackageVersion                 sql.NullString
	FixedVersion                   sql.NullString
	ArtifactName                   sql.NullString
	ArtifactType                   sql.NullString
	ArtifactPath                   sql.NullString
	FirstSeenAt                    time.Time
	LastSeenAt                     time.Time
	PresentInLatestScan            bool
	Status                         string
	ReferencesJson                 string
	SourceJson                     string
	SlaTrackingEnabled             bool
	SlaReportingEnabled            bool
	GracePeriodEnabled             bool
	GracePeriodPercent             int64
	CriticalSlaDays                int64
	HighSlaDays                    int64
	MediumSlaDays                  int64
	LowSlaDays                     int64
	UnknownSlaDays                 int64
	AssetSlaTrackingEnabled        sql.NullBool
	AssetSlaReportingEnabled       sql.NullBool
	AssetGracePeriodEnabled        sql.NullBool
	AssetGracePeriodPercent        sql.NullInt64
	GroupID                        sql.NullString
	GroupPrimaryIdentifier         sql.NullString
	GroupAdditionalIdentifiersJson sql.NullString
	GroupFirstDetectedAt           sql.NullTime
	GroupStatus                    sql.NullString
}

func (q *Queries) GetFindingRow(ctx context.Context, id string) (GetFindingRowRow, error) {
	row := q.db.QueryRowContext(ctx, getFindingRow, id)
	var i GetFindingRowRow
	err := row.Scan(
		&i.FindingID,
		&i.ProjectID,
		&i.ProjectName,
		&i.ScanTargetID,
		&i.ScanTargetName,
		&i.ScanTargetPath,
		&i.ScanTargetRef,
		&i.ScannerKind,
		&i.ScannerFindingID,
		&i.DedupeKey,
		&i.IdentifiersJson,
		&i.PrimaryIdentifier,
		&i.Severity,
		&i.CvssJson,
		&i.PackageName,
		&i.PackageVersion,
		&i.FixedVersion,
		&i.ArtifactName,
		&i.ArtifactType,
		&i.ArtifactPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PresentInLatestScan,
		&i.Status,
		&i.ReferencesJson,
		&i.SourceJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.AssetSlaTrackingEnabled,
		&i.AssetSlaReportingEnabled,
		&i.AssetGracePeriodEnabled,
		&i.AssetGracePeriodPercent,
		&i.GroupID,
		&i.GroupPrimaryIdentifier,
		&i.GroupAdditionalIdentifiersJson,
		&i.GroupFirstDetectedAt,
		&i.GroupStatus,
	)
	return i, err
}

const listFindingComments = `-- name: ListFindingComments :many
SELECT
    finding_comments.id,
    finding_comments.finding_id,
    finding_comments.project_id,
    finding_comments.author_principal_type,
    finding_comments.author_principal_id,
    users.display_name AS user_display,
    machine_credentials.name AS machine_display,
    finding_comments.body,
    finding_comments.is_system,
    finding_comments.status_from,
    finding_comments.status_to,
    finding_comments.created_at,
    finding_comments.updated_at
FROM finding_comments
LEFT JOIN users ON users.id = finding_comments.author_principal_id
    AND finding_comments.author_principal_type = 'user'
LEFT JOIN machine_credentials ON machine_credentials.id = finding_comments.author_principal_id
    AND finding_comments.author_principal_type = 'machine'
WHERE finding_comments.finding_id = ?
ORDER BY finding_comments.created_at, finding_comments.id
`

type ListFindingCommentsRow struct {
	ID                  string
	FindingID           string
	ProjectID           string
	AuthorPrincipalType string
	AuthorPrincipalID   string
	UserDisplay         sql.NullString
	MachineDisplay      sql.NullString
	Body                string
	IsSystem            bool
	StatusFrom          sql.NullString
	StatusTo            sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ListFindingComments(ctx context.Context, findingID string) ([]ListFindingCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingComments, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingCommentsRow
	for rows.Next() {
		var i ListFindingCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ProjectID,
			&i.AuthorPrincipalType,
			&i.AuthorPrincipalID,
			&i.UserDisplay,
			&i.MachineDisplay,
			&i.Body,
			&i.IsSystem,
			&i.StatusFrom,
			&i.StatusTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingRows = `-- name: ListFindingRows :many
SELECT
    raw_finding_instances.id AS finding_id,
    raw_finding_instances.project_id,
    projects.name AS project_name,
    raw_finding_instances.scan_target_id,
    asset_nodes.name AS scan_target_name,
    asset_nodes.path AS scan_target_path,
    asset_nodes.target_ref AS scan_target_ref,
    raw_finding_instances.scanner_kind,
    raw_finding_instances.scanner_finding_id,
    raw_finding_instances.dedupe_key,
    raw_finding_instances.identifiers_json,
    raw_finding_instances.primary_identifier,
    raw_finding_instances.severity,
    raw_finding_instances.cvss_json,
    raw_finding_instances.package_name,
    raw_finding_instances.package_version,
    raw_finding_instances.fixed_version,
    raw_finding_instances.artifact_name,
    raw_finding_instances.artifact_type,
    raw_finding_instances.artifact_path,
    raw_finding_instances.first_seen_at,
    raw_finding_instances.last_seen_at,
    raw_finding_instances.present_in_latest_scan,
    raw_finding_instances.status,
    raw_finding_instances.references_json,
    raw_finding_instances.source_json,
    projects.sla_tracking_enabled,
    projects.sla_reporting_enabled,
    projects.grace_period_enabled,
    projects.grace_period_percent,
    projects.critical_sla_days,
    projects.high_sla_days,
    projects.medium_sla_days,
    projects.low_sla_days,
    projects.unknown_sla_days,
    asset_nodes.sla_tracking_enabled AS asset_sla_tracking_enabled,
    asset_nodes.sla_reporting_enabled AS asset_sla_reporting_enabled,
    asset_nodes.grace_period_enabled AS asset_grace_period_enabled,
    asset_nodes.grace_period_percent AS asset_grace_period_percent,
    project_vulnerability_groups.id AS group_id,
    project_vulnerability_groups.primary_identifier AS group_primary_identifier,
    project_vulnerability_groups.additional_identifiers_json AS group_additional_identifiers_json,
    project_vulnerability_groups.first_detected_at AS group_first_detected_at,
    project_vulnerability_groups.status AS group_status
FROM raw_finding_instances
JOIN projects ON projects.id = raw_finding_instances.project_id
JOIN asset_nodes ON asset_nodes.id = raw_finding_instances.scan_target_id
LEFT JOIN project_vulnerability_groups ON
    project_vulnerability_groups.project_id = raw_finding_instances.project_id
    AND project_vulnerability_groups.dedupe_key = raw_finding_instances.primary_identifier
ORDER BY raw_finding_instances.last_seen_at DESC, raw_finding_instances.primary_identifier, raw_finding_instances.id
`

type ListFindingRowsRow struct {
	FindingID                      string
	ProjectID                      string
	ProjectName                    string
	ScanTargetID                   string
	ScanTargetName                 string
	ScanTargetPath                 string
	ScanTargetRef                  sql.NullString
	ScannerKind                    string
	ScannerFindingID               string
	DedupeKey                      string
	IdentifiersJson                string
	PrimaryIdentifier              string
	Severity                       string
	CvssJson                       string
	PackageName                    sql.NullString
	PackageVersion                 sql.NullString
	FixedVersion                   sql.NullString
	ArtifactName                   sql.NullString
	ArtifactType                   sql.NullString
	ArtifactPath                   sql.NullString
	FirstSeenAt                    time.Time
	LastSeenAt                     time.Time
	PresentInLatestScan            bool
	Status                         string
	ReferencesJson                 string
	SourceJson                     string
	SlaTrackingEnabled             bool
	SlaReportingEnabled            bool
	GracePeriodEnabled             bool
	GracePeriodPercent             int64
	CriticalSlaDays                int64
	HighSlaDays                    int64
	MediumSlaDays                  int64
	LowSlaDays                     int64
	UnknownSlaDays                 int64
	AssetSlaTrackingEnabled        sql.NullBool
	AssetSlaReportingEnabled       sql.NullBool
	AssetGracePeriodEnabled        sql.NullBool
	AssetGracePeriodPercent        sql.NullInt64
	GroupID                        sql.NullString
	GroupPrimaryIdentifier         sql.NullString
	GroupAdditionalIdentifiersJson sql.NullString
	GroupFirstDetectedAt           sql.NullTime
	GroupStatus                    sql.NullString
}

func (q *Queries) ListFindingRows(ctx context.Context) ([]ListFindingRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingRowsRow
	for rows.Next() {
		var i ListFindingRowsRow
		if err := rows.Scan(
			&i.FindingID,
			&i.ProjectID,
			&i.ProjectName,
			&i.ScanTargetID,
			&i.ScanTargetName,
			&i.ScanTargetPath,
			&i.ScanTargetRef,
			&i.ScannerKind,
			&i.ScannerFindingID,
			&i.DedupeKey,
			&i.IdentifiersJson,
			&i.PrimaryIdentifier,
			&i.Severity,
			&i.CvssJson,
			&i.PackageName,
			&i.PackageVersion,
			&i.FixedVersion,
			&i.ArtifactName,
			&i.ArtifactType,
			&i.ArtifactPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PresentInLatestScan,
			&i.Status,
			&i.ReferencesJson,
			&i.SourceJson,
			&i.SlaTrackingEnabled,
			&i.SlaReportingEnabled,
			&i.GracePeriodEnabled,
			&i.GracePeriodPercent,
			&i.CriticalSlaDays,
			&i.HighSlaDays,
			&i.MediumSlaDays,
			&i.LowSlaDays,
			&i.UnknownSlaDays,
			&i.AssetSlaTrackingEnabled,
			&i.AssetSlaReportingEnabled,
			&i.AssetGracePeriodEnabled,
			&i.AssetGracePeriodPercent,
			&i.GroupID,
			&i.GroupPrimaryIdentifier,
			&i.GroupAdditionalIdentifiersJson,
			&i.GroupFirstDetectedAt,
			&i.GroupStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingStatusChangeRequests = `-- name: ListFindingStatusChangeRequests :many
SELECT
    finding_status_change_requests.id,
    finding_status_change_requests.finding_id,
    finding_status_change_requests.project_id,
    finding_status_change_requests.requester_principal_type,
    finding_status_change_requests.requester_principal_id,
    requester_user.display_name AS requester_user_display,
    requester_machine.name AS requester_machine_display,
    finding_status_change_requests.reviewer_principal_type,
    finding_status_change_requests.reviewer_principal_id,
    reviewer_user.display_name AS reviewer_user_display,
    reviewer_machine.name AS reviewer_machine_display,
    finding_status_change_requests.from_status,
    finding_status_change_requests.to_status,
    finding_status_change_requests.state,
    finding_status_change_requests.comment,
    finding_status_change_requests.decision_comment,
    finding_status_change_requests.decided_at,
    finding_status_change_requests.created_at,
    finding_status_change_requests.updated_at
FROM finding_status_change_requests
LEFT JOIN users AS requester_user ON requester_user.id = finding_status_change_requests.requester_principal_id
    AND finding_status_change_requests.requester_principal_type = 'user'
LEFT JOIN machine_credentials AS requester_machine ON requester_machine.id = finding_status_change_requests.requester_principal_id
    AND finding_status_change_requests.requester_principal_type = 'machine'
LEFT JOIN users AS reviewer_user ON reviewer_user.id = finding_status_change_requests.reviewer_principal_id
    AND finding_status_change_requests.reviewer_principal_type = 'user'
LEFT JOIN machine_credentials AS reviewer_machine ON reviewer_machine.id = finding_status_change_requests.reviewer_principal_id
    AND finding_status_change_requests.reviewer_principal_type = 'machine'
WHERE finding_status_change_requests.finding_id = ?
ORDER BY finding_status_change_requests.created_at, finding_status_change_requests.id
`

type ListFindingStatusChangeRequestsRow struct {
	ID                      string
	FindingID               string
	ProjectID               string
	RequesterPrincipalType  string
	RequesterPrincipalID    string
	RequesterUserDisplay    sql.NullString
	RequesterMachineDisplay sql.NullString
	ReviewerPrincipalType   sql.NullString
	ReviewerPrincipalID     sql.NullString
	ReviewerUserDisplay     sql.NullString
	ReviewerMachineDisplay  sql.NullString
	FromStatus              string
	ToStatus                string
	State                   string
	Comment                 sql.NullString
	DecisionComment         sql.NullString
	DecidedAt               sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) ListFindingStatusChangeRequests(ctx context.Context, findingID string) ([]ListFindingStatusChangeRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingStatusChangeRequests, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingStatusChangeRequestsRow
	for rows.Next() {
		var i ListFindingStatusChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ProjectID,
			&i.RequesterPrincipalType,
			&i.RequesterPrincipalID,
			&i.RequesterUserDisplay,
			&i.RequesterMachineDisplay,
			&i.ReviewerPrincipalType,
			&i.ReviewerPrincipalID,
			&i.ReviewerUserDisplay,
			&i.ReviewerMachineDisplay,
			&i.FromStatus,
			&i.ToStatus,
			&i.State,
			&i.Comment,
			&i.DecisionComment,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
