// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createImportAttempt = `-- name: CreateImportAttempt :one
INSERT INTO import_attempts (
    id,
    project_id,
    asset_node_id,
    uploader_principal_type,
    uploader_principal_id,
    status,
    parser_name,
    sanitized_message,
    correlation_id,
    metadata_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    project_id,
    asset_node_id,
    uploader_principal_type,
    uploader_principal_id,
    status,
    parser_name,
    sanitized_message,
    correlation_id,
    metadata_json,
    created_at,
    updated_at
`

type CreateImportAttemptParams struct {
	ID                    string
	ProjectID             string
	AssetNodeID           sql.NullString
	UploaderPrincipalType sql.NullString
	UploaderPrincipalID   sql.NullString
	Status                string
	ParserName            string
	SanitizedMessage      sql.NullString
	CorrelationID         sql.NullString
	MetadataJson          string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreateImportAttempt(ctx context.Context, arg CreateImportAttemptParams) (ImportAttempt, error) {
	row := q.db.QueryRowContext(ctx, createImportAttempt,
		arg.ID,
		arg.ProjectID,
		arg.AssetNodeID,
		arg.UploaderPrincipalType,
		arg.UploaderPrincipalID,
		arg.Status,
		arg.ParserName,
		arg.SanitizedMessage,
		arg.CorrelationID,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ImportAttempt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssetNodeID,
		&i.UploaderPrincipalType,
		&i.UploaderPrincipalID,
		&i.Status,
		&i.ParserName,
		&i.SanitizedMessage,
		&i.CorrelationID,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectVulnerabilityGroup = `-- name: CreateProjectVulnerabilityGroup :one
INSERT INTO project_vulnerability_groups (
    id,
    project_id,
    primary_identifier,
    additional_identifiers_json,
    first_detected_at,
    severity,
    status,
    dedupe_key,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, dedupe_key) DO UPDATE SET
    severity = excluded.severity,
    updated_at = excluded.updated_at
RETURNING
    id,
    project_id,
    primary_identifier,
    additional_identifiers_json,
    first_detected_at,
    severity,
    status,
    dedupe_key,
    created_at,
    updated_at
`

type CreateProjectVulnerabilityGroupParams struct {
	ID                        string
	ProjectID                 string
	PrimaryIdentifier         string
	AdditionalIdentifiersJson string
	FirstDetectedAt           time.Time
	Severity                  string
	Status                    string
	DedupeKey                 string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

func (q *Queries) CreateProjectVulnerabilityGroup(ctx context.Context, arg CreateProjectVulnerabilityGroupParams) (ProjectVulnerabilityGroup, error) {
	row := q.db.QueryRowContext(ctx, createProjectVulnerabilityGroup,
		arg.ID,
		arg.ProjectID,
		arg.PrimaryIdentifier,
		arg.AdditionalIdentifiersJson,
		arg.FirstDetectedAt,
		arg.Severity,
		arg.Status,
		arg.DedupeKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProjectVulnerabilityGroup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PrimaryIdentifier,
		&i.AdditionalIdentifiersJson,
		&i.FirstDetectedAt,
		&i.Severity,
		&i.Status,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRawFindingInstance = `-- name: CreateRawFindingInstance :one
INSERT INTO raw_finding_instances (
    id,
    project_id,
    scan_id,
    scan_target_id,
    scanner_kind,
    scanner_finding_id,
    dedupe_key,
    identifiers_json,
    primary_identifier,
    severity,
    cvss_json,
    package_name,
    package_version,
    fixed_version,
    artifact_name,
    artifact_type,
    artifact_path,
    first_seen_at,
    last_seen_at,
    present_in_latest_scan,
    status,
    references_json,
    source_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (scan_target_id, dedupe_key) DO UPDATE SET
    scan_id = excluded.scan_id,
    last_seen_at = excluded.last_seen_at,
    present_in_latest_scan = excluded.present_in_latest_scan,
    severity = excluded.severity,
    updated_at = excluded.updated_at
RETURNING
    id,
    project_id,
    scan_id,
    scan_target_id,
    scanner_kind,
    scanner_finding_id,
    dedupe_key,
    identifiers_json,
    primary_identifier,
    severity,
    cvss_json,
    package_name,
    package_version,
    fixed_version,
    artifact_name,
    artifact_type,
    artifact_path,
    first_seen_at,
    last_seen_at,
    present_in_latest_scan,
    status,
    references_json,
    source_json,
    created_at,
    updated_at
`

type CreateRawFindingInstanceParams struct {
	ID                  string
	ProjectID           string
	ScanID              string
	ScanTargetID        string
	ScannerKind         string
	ScannerFindingID    string
	DedupeKey           string
	IdentifiersJson     string
	PrimaryIdentifier   string
	Severity            string
	CvssJson            string
	PackageName         sql.NullString
	PackageVersion      sql.NullString
	FixedVersion        sql.NullString
	ArtifactName        sql.NullString
	ArtifactType        sql.NullString
	ArtifactPath        sql.NullString
	FirstSeenAt         time.Time
	LastSeenAt          time.Time
	PresentInLatestScan bool
	Status              string
	ReferencesJson      string
	SourceJson          string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateRawFindingInstance(ctx context.Context, arg CreateRawFindingInstanceParams) (RawFindingInstance, error) {
	row := q.db.QueryRowContext(ctx, createRawFindingInstance,
		arg.ID,
		arg.ProjectID,
		arg.ScanID,
		arg.ScanTargetID,
		arg.ScannerKind,
		arg.ScannerFindingID,
		arg.DedupeKey,
		arg.IdentifiersJson,
		arg.PrimaryIdentifier,
		arg.Severity,
		arg.CvssJson,
		arg.PackageName,
		arg.PackageVersion,
		arg.FixedVersion,
		arg.ArtifactName,
		arg.ArtifactType,
		arg.ArtifactPath,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.PresentInLatestScan,
		arg.Status,
		arg.ReferencesJson,
		arg.SourceJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RawFindingInstance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanID,
		&i.ScanTargetID,
		&i.ScannerKind,
		&i.ScannerFindingID,
		&i.DedupeKey,
		&i.IdentifiersJson,
		&i.PrimaryIdentifier,
		&i.Severity,
		&i.CvssJson,
		&i.PackageName,
		&i.PackageVersion,
		&i.FixedVersion,
		&i.ArtifactName,
		&i.ArtifactType,
		&i.ArtifactPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PresentInLatestScan,
		&i.Status,
		&i.ReferencesJson,
		&i.SourceJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
    id,
    project_id,
    scan_target_id,
    scanner_kind,
    report_kind,
    parser_version,
    scan_started_at,
    scan_finished_at,
    metadata_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    project_id,
    scan_target_id,
    scanner_kind,
    report_kind,
    parser_version,
    scan_started_at,
    scan_finished_at,
    metadata_json,
    created_at,
    updated_at
`

type CreateScanParams struct {
	ID             string
	ProjectID      string
	ScanTargetID   string
	ScannerKind    string
	ReportKind     string
	ParserVersion  string
	ScanStartedAt  sql.NullTime
	ScanFinishedAt sql.NullTime
	MetadataJson   string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan,
		arg.ID,
		arg.ProjectID,
		arg.ScanTargetID,
		arg.ScannerKind,
		arg.ReportKind,
		arg.ParserVersion,
		arg.ScanStartedAt,
		arg.ScanFinishedAt,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanTargetID,
		&i.ScannerKind,
		&i.ReportKind,
		&i.ParserVersion,
		&i.ScanStartedAt,
		&i.ScanFinishedAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminImportAttempts = `-- name: ListAdminImportAttempts :many
SELECT
    import_attempts.id,
    import_attempts.project_id,
    projects.name AS project_name,
    import_attempts.asset_node_id,
    asset_nodes.name AS asset_name,
    asset_nodes.path AS asset_path,
    import_attempts.uploader_principal_type,
    import_attempts.uploader_principal_id,
    users.display_name AS user_display,
    machine_credentials.name AS machine_display,
    import_attempts.status,
    import_attempts.parser_name,
    import_attempts.sanitized_message,
    import_attempts.correlation_id,
    import_attempts.metadata_json,
    import_attempts.created_at,
    import_attempts.updated_at
FROM import_attempts
JOIN projects ON projects.id = import_attempts.project_id
LEFT JOIN asset_nodes ON asset_nodes.id = import_attempts.asset_node_id
LEFT JOIN users ON users.id = import_attempts.uploader_principal_id
    AND import_attempts.uploader_principal_type = 'user'
LEFT JOIN machine_credentials ON machine_credentials.id = import_attempts.uploader_principal_id
    AND import_attempts.uploader_principal_type = 'machine'
ORDER BY import_attempts.created_at DESC
LIMIT ?
`

type ListAdminImportAttemptsRow struct {
	ID                    string
	ProjectID             string
	ProjectName           string
	AssetNodeID           sql.NullString
	AssetName             sql.NullString
	AssetPath             sql.NullString
	UploaderPrincipalType sql.NullString
	UploaderPrincipalID   sql.NullString
	UserDisplay           sql.NullString
	MachineDisplay        sql.NullString
	Status                string
	ParserName            string
	SanitizedMessage      sql.NullString
	CorrelationID         sql.NullString
	MetadataJson          string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) ListAdminImportAttempts(ctx context.Context, limit int64) ([]ListAdminImportAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminImportAttempts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminImportAttemptsRow
	for rows.Next() {
		var i ListAdminImportAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.AssetNodeID,
			&i.AssetName,
			&i.AssetPath,
			&i.UploaderPrincipalType,
			&i.UploaderPrincipalID,
			&i.UserDisplay,
			&i.MachineDisplay,
			&i.Status,
			&i.ParserName,
			&i.SanitizedMessage,
			&i.CorrelationID,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
