// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countProjectAssets = `-- name: CountProjectAssets :one
SELECT count(*)
FROM asset_nodes
WHERE project_id = ?
`

func (q *Queries) CountProjectAssets(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectAssets, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssetNode = `-- name: CreateAssetNode :one
INSERT INTO asset_nodes (
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
`

type CreateAssetNodeParams struct {
	ID                  string
	ProjectID           string
	ParentID            sql.NullString
	NodeType            string
	Name                string
	Path                string
	TargetRef           sql.NullString
	MetadataJson        string
	SlaTrackingEnabled  sql.NullBool
	SlaReportingEnabled sql.NullBool
	GracePeriodEnabled  sql.NullBool
	GracePeriodPercent  sql.NullInt64
	SortOrder           int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateAssetNode(ctx context.Context, arg CreateAssetNodeParams) (AssetNode, error) {
	row := q.db.QueryRowContext(ctx, createAssetNode,
		arg.ID,
		arg.ProjectID,
		arg.ParentID,
		arg.NodeType,
		arg.Name,
		arg.Path,
		arg.TargetRef,
		arg.MetadataJson,
		arg.SlaTrackingEnabled,
		arg.SlaReportingEnabled,
		arg.GracePeriodEnabled,
		arg.GracePeriodPercent,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AssetNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.NodeType,
		&i.Name,
		&i.Path,
		&i.TargetRef,
		&i.MetadataJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 30, 60, 90, 180, 365, ?, ?)
RETURNING
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
`

type CreateProjectParams struct {
	ID                                string
	Slug                              string
	Name                              string
	Description                       sql.NullString
	SlaTrackingEnabled                bool
	SlaReportingEnabled               bool
	GracePeriodEnabled                bool
	GracePeriodPercent                int64
	RequirePeerReviewForStatusChanges bool
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.SlaTrackingEnabled,
		arg.SlaReportingEnabled,
		arg.GracePeriodEnabled,
		arg.GracePeriodPercent,
		arg.RequirePeerReviewForStatusChanges,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.RequirePeerReviewForStatusChanges,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssetSubtree = `-- name: DeleteAssetSubtree :exec
DELETE FROM asset_nodes
WHERE project_id = ? AND (id = ? OR path LIKE ?)
`

type DeleteAssetSubtreeParams struct {
	ProjectID string
	ID        string
	Path      string
}

func (q *Queries) DeleteAssetSubtree(ctx context.Context, arg DeleteAssetSubtreeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssetSubtree, arg.ProjectID, arg.ID, arg.Path)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectAssets = `-- name: DeleteProjectAssets :exec
DELETE FROM asset_nodes
WHERE project_id = ?
`

func (q *Queries) DeleteProjectAssets(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectAssets, projectID)
	return err
}

const getAssetNode = `-- name: GetAssetNode :one
SELECT
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
FROM asset_nodes
WHERE id = ?
`

func (q *Queries) GetAssetNode(ctx context.Context, id string) (AssetNode, error) {
	row := q.db.QueryRowContext(ctx, getAssetNode, id)
	var i AssetNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.NodeType,
		&i.Name,
		&i.Path,
		&i.TargetRef,
		&i.MetadataJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.RequirePeerReviewForStatusChanges,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectAssetByPath = `-- name: GetProjectAssetByPath :one
SELECT
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
FROM asset_nodes
WHERE project_id = ? AND path = ?
`

type GetProjectAssetByPathParams struct {
	ProjectID string
	Path      string
}

func (q *Queries) GetProjectAssetByPath(ctx context.Context, arg GetProjectAssetByPathParams) (AssetNode, error) {
	row := q.db.QueryRowContext(ctx, getProjectAssetByPath, arg.ProjectID, arg.Path)
	var i AssetNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.NodeType,
		&i.Name,
		&i.Path,
		&i.TargetRef,
		&i.MetadataJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectIdentityConflict = `-- name: GetProjectIdentityConflict :one
SELECT
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
FROM projects
WHERE id != ? AND (slug = ? OR name = ?)
LIMIT 1
`

type GetProjectIdentityConflictParams struct {
	ID   string
	Slug string
	Name string
}

func (q *Queries) GetProjectIdentityConflict(ctx context.Context, arg GetProjectIdentityConflictParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectIdentityConflict, arg.ID, arg.Slug, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.RequirePeerReviewForStatusChanges,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetSubtree = `-- name: ListAssetSubtree :many
SELECT
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
FROM asset_nodes
WHERE project_id = ? AND (id = ? OR path LIKE ?)
ORDER BY path DESC
`

type ListAssetSubtreeParams struct {
	ProjectID string
	ID        string
	Path      string
}

func (q *Queries) ListAssetSubtree(ctx context.Context, arg ListAssetSubtreeParams) ([]AssetNode, error) {
	rows, err := q.db.QueryContext(ctx, listAssetSubtree, arg.ProjectID, arg.ID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetNode
	for rows.Next() {
		var i AssetNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.NodeType,
			&i.Name,
			&i.Path,
			&i.TargetRef,
			&i.MetadataJson,
			&i.SlaTrackingEnabled,
			&i.SlaReportingEnabled,
			&i.GracePeriodEnabled,
			&i.GracePeriodPercent,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectAssets = `-- name: ListProjectAssets :many
SELECT
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
FROM asset_nodes
WHERE project_id = ?
ORDER BY path
`

func (q *Queries) ListProjectAssets(ctx context.Context, projectID string) ([]AssetNode, error) {
	rows, err := q.db.QueryContext(ctx, listProjectAssets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetNode
	for rows.Next() {
		var i AssetNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.NodeType,
			&i.Name,
			&i.Path,
			&i.TargetRef,
			&i.MetadataJson,
			&i.SlaTrackingEnabled,
			&i.SlaReportingEnabled,
			&i.GracePeriodEnabled,
			&i.GracePeriodPercent,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
FROM projects
ORDER BY name, slug
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SlaTrackingEnabled,
			&i.SlaReportingEnabled,
			&i.GracePeriodEnabled,
			&i.GracePeriodPercent,
			&i.RequirePeerReviewForStatusChanges,
			&i.CriticalSlaDays,
			&i.HighSlaDays,
			&i.MediumSlaDays,
			&i.LowSlaDays,
			&i.UnknownSlaDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetNode = `-- name: UpdateAssetNode :one
UPDATE asset_nodes
SET
    parent_id = ?,
    name = ?,
    path = ?,
    sla_tracking_enabled = ?,
    sla_reporting_enabled = ?,
    grace_period_enabled = ?,
    grace_period_percent = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    project_id,
    parent_id,
    node_type,
    name,
    path,
    target_ref,
    metadata_json,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    sort_order,
    created_at,
    updated_at
`

type UpdateAssetNodeParams struct {
	ParentID            sql.NullString
	Name                string
	Path                string
	SlaTrackingEnabled  sql.NullBool
	SlaReportingEnabled sql.NullBool
	GracePeriodEnabled  sql.NullBool
	GracePeriodPercent  sql.NullInt64
	UpdatedAt           time.Time
	ID                  string
}

func (q *Queries) UpdateAssetNode(ctx context.Context, arg UpdateAssetNodeParams) (AssetNode, error) {
	row := q.db.QueryRowContext(ctx, updateAssetNode,
		arg.ParentID,
		arg.Name,
		arg.Path,
		arg.SlaTrackingEnabled,
		arg.SlaReportingEnabled,
		arg.GracePeriodEnabled,
		arg.GracePeriodPercent,
		arg.UpdatedAt,
		arg.ID,
	)
	var i AssetNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.NodeType,
		&i.Name,
		&i.Path,
		&i.TargetRef,
		&i.MetadataJson,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetPath = `-- name: UpdateAssetPath :exec
UPDATE asset_nodes
SET
    path = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAssetPathParams struct {
	Path      string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateAssetPath(ctx context.Context, arg UpdateAssetPathParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetPath, arg.Path, arg.UpdatedAt, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    slug = ?,
    name = ?,
    sla_tracking_enabled = ?,
    sla_reporting_enabled = ?,
    grace_period_enabled = ?,
    grace_period_percent = ?,
    require_peer_review_for_status_changes = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    slug,
    name,
    description,
    sla_tracking_enabled,
    sla_reporting_enabled,
    grace_period_enabled,
    grace_period_percent,
    require_peer_review_for_status_changes,
    critical_sla_days,
    high_sla_days,
    medium_sla_days,
    low_sla_days,
    unknown_sla_days,
    created_at,
    updated_at
`

type UpdateProjectParams struct {
	Slug                              string
	Name                              string
	SlaTrackingEnabled                bool
	SlaReportingEnabled               bool
	GracePeriodEnabled                bool
	GracePeriodPercent                int64
	RequirePeerReviewForStatusChanges bool
	UpdatedAt                         time.Time
	ID                                string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Slug,
		arg.Name,
		arg.SlaTrackingEnabled,
		arg.SlaReportingEnabled,
		arg.GracePeriodEnabled,
		arg.GracePeriodPercent,
		arg.RequirePeerReviewForStatusChanges,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SlaTrackingEnabled,
		&i.SlaReportingEnabled,
		&i.GracePeriodEnabled,
		&i.GracePeriodPercent,
		&i.RequirePeerReviewForStatusChanges,
		&i.CriticalSlaDays,
		&i.HighSlaDays,
		&i.MediumSlaDays,
		&i.LowSlaDays,
		&i.UnknownSlaDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
