// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package dbgen

import (
	"context"
)

const getMachineCredential = `-- name: GetMachineCredential :one
SELECT
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
FROM machine_credentials
WHERE id = ?
`

func (q *Queries) GetMachineCredential(ctx context.Context, id string) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, getMachineCredential, id)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineTokenByDigest = `-- name: GetMachineTokenByDigest :one
SELECT
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM machine_tokens
WHERE token_digest = ?
`

func (q *Queries) GetMachineTokenByDigest(ctx context.Context, tokenDigest string) (MachineToken, error) {
	row := q.db.QueryRowContext(ctx, getMachineTokenByDigest, tokenDigest)
	var i MachineToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
