// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createMachineCredential = `-- name: CreateMachineCredential :one
INSERT INTO machine_credentials (
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
`

type CreateMachineCredentialParams struct {
	ID                 string
	Name               string
	ClientID           string
	ClientSecretDigest string
	IsActive           bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateMachineCredential(ctx context.Context, arg CreateMachineCredentialParams) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, createMachineCredential,
		arg.ID,
		arg.Name,
		arg.ClientID,
		arg.ClientSecretDigest,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMachineRefreshToken = `-- name: CreateMachineRefreshToken :one
INSERT INTO machine_refresh_tokens (
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type CreateMachineRefreshTokenParams struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateMachineRefreshToken(ctx context.Context, arg CreateMachineRefreshTokenParams) (MachineRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createMachineRefreshToken,
		arg.ID,
		arg.MachineCredentialID,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MachineRefreshToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMachineToken = `-- name: CreateMachineToken :one
INSERT INTO machine_tokens (
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type CreateMachineTokenParams struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateMachineToken(ctx context.Context, arg CreateMachineTokenParams) (MachineToken, error) {
	row := q.db.QueryRowContext(ctx, createMachineToken,
		arg.ID,
		arg.MachineCredentialID,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MachineToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineCredential = `-- name: GetMachineCredential :one
SELECT
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
FROM machine_credentials
WHERE id = ?
`

func (q *Queries) GetMachineCredential(ctx context.Context, id string) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, getMachineCredential, id)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineCredentialByClientID = `-- name: GetMachineCredentialByClientID :one
SELECT
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
FROM machine_credentials
WHERE client_id = ?
`

func (q *Queries) GetMachineCredentialByClientID(ctx context.Context, clientID string) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, getMachineCredentialByClientID, clientID)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineRefreshTokenByDigest = `-- name: GetMachineRefreshTokenByDigest :one
SELECT
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM machine_refresh_tokens
WHERE token_digest = ?
`

func (q *Queries) GetMachineRefreshTokenByDigest(ctx context.Context, tokenDigest string) (MachineRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getMachineRefreshTokenByDigest, tokenDigest)
	var i MachineRefreshToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineTokenByDigest = `-- name: GetMachineTokenByDigest :one
SELECT
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM machine_tokens
WHERE token_digest = ?
`

func (q *Queries) GetMachineTokenByDigest(ctx context.Context, tokenDigest string) (MachineToken, error) {
	row := q.db.QueryRowContext(ctx, getMachineTokenByDigest, tokenDigest)
	var i MachineToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachineCredentials = `-- name: ListMachineCredentials :many
SELECT
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
FROM machine_credentials
ORDER BY created_at
`

func (q *Queries) ListMachineCredentials(ctx context.Context) ([]MachineCredential, error) {
	rows, err := q.db.QueryContext(ctx, listMachineCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MachineCredential
	for rows.Next() {
		var i MachineCredential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientSecretDigest,
			&i.IsActive,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMachineAccessTokensForCredential = `-- name: RevokeMachineAccessTokensForCredential :exec
UPDATE machine_tokens
SET
    revoked_at = ?,
    updated_at = ?
WHERE machine_credential_id = ? AND revoked_at IS NULL
`

type RevokeMachineAccessTokensForCredentialParams struct {
	RevokedAt           sql.NullTime
	UpdatedAt           time.Time
	MachineCredentialID string
}

func (q *Queries) RevokeMachineAccessTokensForCredential(ctx context.Context, arg RevokeMachineAccessTokensForCredentialParams) error {
	_, err := q.db.ExecContext(ctx, revokeMachineAccessTokensForCredential, arg.RevokedAt, arg.UpdatedAt, arg.MachineCredentialID)
	return err
}

const revokeMachineCredential = `-- name: RevokeMachineCredential :one
UPDATE machine_credentials
SET
    is_active = false,
    revoked_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
`

type RevokeMachineCredentialParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RevokeMachineCredential(ctx context.Context, arg RevokeMachineCredentialParams) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, revokeMachineCredential, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeMachineRefreshToken = `-- name: RevokeMachineRefreshToken :one
UPDATE machine_refresh_tokens
SET
    revoked_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    machine_credential_id,
    token_digest,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type RevokeMachineRefreshTokenParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RevokeMachineRefreshToken(ctx context.Context, arg RevokeMachineRefreshTokenParams) (MachineRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeMachineRefreshToken, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	var i MachineRefreshToken
	err := row.Scan(
		&i.ID,
		&i.MachineCredentialID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeMachineRefreshTokensForCredential = `-- name: RevokeMachineRefreshTokensForCredential :exec
UPDATE machine_refresh_tokens
SET
    revoked_at = ?,
    updated_at = ?
WHERE machine_credential_id = ? AND revoked_at IS NULL
`

type RevokeMachineRefreshTokensForCredentialParams struct {
	RevokedAt           sql.NullTime
	UpdatedAt           time.Time
	MachineCredentialID string
}

func (q *Queries) RevokeMachineRefreshTokensForCredential(ctx context.Context, arg RevokeMachineRefreshTokensForCredentialParams) error {
	_, err := q.db.ExecContext(ctx, revokeMachineRefreshTokensForCredential, arg.RevokedAt, arg.UpdatedAt, arg.MachineCredentialID)
	return err
}

const updateMachineCredentialSecret = `-- name: UpdateMachineCredentialSecret :one
UPDATE machine_credentials
SET
    client_secret_digest = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    name,
    client_id,
    client_secret_digest,
    is_active,
    revoked_at,
    created_at,
    updated_at
`

type UpdateMachineCredentialSecretParams struct {
	ClientSecretDigest string
	UpdatedAt          time.Time
	ID                 string
}

func (q *Queries) UpdateMachineCredentialSecret(ctx context.Context, arg UpdateMachineCredentialSecretParams) (MachineCredential, error) {
	row := q.db.QueryRowContext(ctx, updateMachineCredentialSecret, arg.ClientSecretDigest, arg.UpdatedAt, arg.ID)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretDigest,
		&i.IsActive,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
