// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type AppSecuritySetting struct {
	ID                              string
	ForcePeerReviewForStatusChanges bool
	SessionIdleTimeoutMinutes       sql.NullInt64
	SessionAbsoluteTimeoutMinutes   sql.NullInt64
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

type MachineCredential struct {
	ID                 string
	Name               string
	ClientID           string
	ClientSecretDigest string
	IsActive           bool
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type MachineToken struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	RevokedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type UserSession struct {
	ID            string
	UserID        string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	RevokedAt     sql.NullTime
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
