// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type AppSecuritySetting struct {
	ID                              string
	ForcePeerReviewForStatusChanges bool
	SessionIdleTimeoutMinutes       sql.NullInt64
	SessionAbsoluteTimeoutMinutes   sql.NullInt64
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

type AuditLogEvent struct {
	ID                 string
	EventType          string
	ActorPrincipalType sql.NullString
	ActorPrincipalID   sql.NullString
	ActorDisplay       sql.NullString
	TargetType         sql.NullString
	TargetID           sql.NullString
	ProjectID          sql.NullString
	IpAddress          sql.NullString
	UserAgent          sql.NullString
	MetadataJson       string
	CreatedAt          time.Time
}

type Group struct {
	ID          string
	Name        string
	DisplayName string
	IsProtected bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMembership struct {
	ID            string
	GroupID       string
	PrincipalType string
	PrincipalID   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MachineCredential struct {
	ID                 string
	Name               string
	ClientID           string
	ClientSecretDigest string
	IsActive           bool
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type MachineRefreshToken struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	RevokedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type MachineToken struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	RevokedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PermissionAssignment struct {
	ID            string
	PrincipalType string
	PrincipalID   string
	Permission    string
	Effect        string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID          string
	Username    string
	DisplayName string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserPasswordCredential struct {
	ID           string
	UserID       string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserSession struct {
	ID            string
	UserID        string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	RevokedAt     sql.NullTime
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
