// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type AppSecuritySetting struct {
	ID                              string
	ForcePeerReviewForStatusChanges bool
	SessionIdleTimeoutMinutes       sql.NullInt64
	SessionAbsoluteTimeoutMinutes   sql.NullInt64
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

type AssetNode struct {
	ID                  string
	ProjectID           string
	ParentID            sql.NullString
	NodeType            string
	Name                string
	Path                string
	TargetRef           sql.NullString
	MetadataJson        string
	SlaTrackingEnabled  sql.NullBool
	SlaReportingEnabled sql.NullBool
	GracePeriodEnabled  sql.NullBool
	GracePeriodPercent  sql.NullInt64
	SortOrder           int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AuditLogEvent struct {
	ID                 string
	EventType          string
	ActorPrincipalType sql.NullString
	ActorPrincipalID   sql.NullString
	ActorDisplay       sql.NullString
	TargetType         sql.NullString
	TargetID           sql.NullString
	ProjectID          sql.NullString
	IpAddress          sql.NullString
	UserAgent          sql.NullString
	MetadataJson       string
	CreatedAt          time.Time
}

type Group struct {
	ID          string
	Name        string
	DisplayName string
	IsProtected bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMembership struct {
	ID            string
	GroupID       string
	PrincipalType string
	PrincipalID   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ImportAttempt struct {
	ID                    string
	ProjectID             string
	AssetNodeID           sql.NullString
	UploaderPrincipalType sql.NullString
	UploaderPrincipalID   sql.NullString
	Status                string
	ParserName            string
	SanitizedMessage      sql.NullString
	CorrelationID         sql.NullString
	MetadataJson          string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type MachineCredential struct {
	ID                 string
	Name               string
	ClientID           string
	ClientSecretDigest string
	IsActive           bool
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type MachineRefreshToken struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	RevokedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type MachineToken struct {
	ID                  string
	MachineCredentialID string
	TokenDigest         string
	ExpiresAt           time.Time
	RevokedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PermissionAssignment struct {
	ID            string
	PrincipalType string
	PrincipalID   string
	Permission    string
	Effect        string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Project struct {
	ID                                string
	Slug                              string
	Name                              string
	Description                       sql.NullString
	SlaTrackingEnabled                bool
	SlaReportingEnabled               bool
	GracePeriodEnabled                bool
	GracePeriodPercent                int64
	RequirePeerReviewForStatusChanges bool
	CriticalSlaDays                   int64
	HighSlaDays                       int64
	MediumSlaDays                     int64
	LowSlaDays                        int64
	UnknownSlaDays                    int64
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
}

type ProjectVulnerabilityGroup struct {
	ID                        string
	ProjectID                 string
	PrimaryIdentifier         string
	AdditionalIdentifiersJson string
	FirstDetectedAt           time.Time
	Severity                  string
	Status                    string
	DedupeKey                 string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type RawFindingInstance struct {
	ID                  string
	ProjectID           string
	ScanID              string
	ScanTargetID        string
	ScannerKind         string
	ScannerFindingID    string
	DedupeKey           string
	IdentifiersJson     string
	PrimaryIdentifier   string
	Severity            string
	CvssJson            string
	PackageName         sql.NullString
	PackageVersion      sql.NullString
	FixedVersion        sql.NullString
	ArtifactName        sql.NullString
	ArtifactType        sql.NullString
	ArtifactPath        sql.NullString
	FirstSeenAt         time.Time
	LastSeenAt          time.Time
	PresentInLatestScan bool
	Status              string
	ReferencesJson      string
	SourceJson          string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Scan struct {
	ID             string
	ProjectID      string
	ScanTargetID   string
	ScannerKind    string
	ReportKind     string
	ParserVersion  string
	ScanStartedAt  sql.NullTime
	ScanFinishedAt sql.NullTime
	MetadataJson   string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID          string
	Username    string
	DisplayName string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserPasswordCredential struct {
	ID           string
	UserID       string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserSession struct {
	ID            string
	UserID        string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	RevokedAt     sql.NullTime
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
