// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getGroupName = `-- name: GetGroupName :one
SELECT name
FROM groups
WHERE id = ?
`

func (q *Queries) GetGroupName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listGroupIDsForPrincipal = `-- name: ListGroupIDsForPrincipal :many
SELECT group_id
FROM group_memberships
WHERE principal_type = ? AND principal_id = ?
`

type ListGroupIDsForPrincipalParams struct {
	PrincipalType string
	PrincipalID   string
}

func (q *Queries) ListGroupIDsForPrincipal(ctx context.Context, arg ListGroupIDsForPrincipalParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGroupIDsForPrincipal, arg.PrincipalType, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingAssignmentsForPrincipal = `-- name: ListMatchingAssignmentsForPrincipal :many
SELECT
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
FROM permission_assignments
WHERE
    principal_type = ?1
    AND principal_id = ?2
    AND permission = ?3
    AND (
        scope_type = ?4
        OR (scope_type IS NULL AND ?4 IS NULL)
    )
    AND (
        scope_id = ?5
        OR (scope_id IS NULL AND ?5 IS NULL)
    )
`

type ListMatchingAssignmentsForPrincipalParams struct {
	PrincipalType string
	PrincipalID   string
	Permission    string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
}

func (q *Queries) ListMatchingAssignmentsForPrincipal(ctx context.Context, arg ListMatchingAssignmentsForPrincipalParams) ([]PermissionAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listMatchingAssignmentsForPrincipal,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.ScopeType,
		arg.ScopeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionAssignment
	for rows.Next() {
		var i PermissionAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.Effect,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
