// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
`

type CreateGroupParams struct {
	ID          string
	Name        string
	DisplayName string
	IsProtected bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.IsProtected,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IsProtected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMembership = `-- name: CreateGroupMembership :one
INSERT INTO group_memberships (
    id,
    group_id,
    principal_type,
    principal_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    group_id,
    principal_type,
    principal_id,
    created_at,
    updated_at
`

type CreateGroupMembershipParams struct {
	ID            string
	GroupID       string
	PrincipalType string
	PrincipalID   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateGroupMembership(ctx context.Context, arg CreateGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRowContext(ctx, createGroupMembership,
		arg.ID,
		arg.GroupID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPermissionAssignment = `-- name: CreatePermissionAssignment :one
INSERT INTO permission_assignments (
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
`

type CreatePermissionAssignmentParams struct {
	ID            string
	PrincipalType string
	PrincipalID   string
	Permission    string
	Effect        string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreatePermissionAssignment(ctx context.Context, arg CreatePermissionAssignmentParams) (PermissionAssignment, error) {
	row := q.db.QueryRowContext(ctx, createPermissionAssignment,
		arg.ID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.Effect,
		arg.ScopeType,
		arg.ScopeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PermissionAssignment
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.Effect,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IsProtected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
FROM groups
WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IsProtected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT
    id,
    group_id,
    principal_type,
    principal_id,
    created_at,
    updated_at
FROM group_memberships
WHERE group_id = $1 AND principal_type = $2 AND principal_id = $3
`

type GetGroupMembershipParams struct {
	GroupID       string
	PrincipalType string
	PrincipalID   string
}

func (q *Queries) GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRowContext(ctx, getGroupMembership, arg.GroupID, arg.PrincipalType, arg.PrincipalID)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupName = `-- name: GetGroupName :one
SELECT name
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getPermissionAssignment = `-- name: GetPermissionAssignment :one
SELECT
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
FROM permission_assignments
WHERE
    principal_type = $1
    AND principal_id = $2
    AND permission = $3
    AND effect = $4
    AND (
        scope_type = $5
        OR (scope_type IS NULL AND $5 IS NULL)
    )
    AND (
        scope_id = $6
        OR (scope_id IS NULL AND $6 IS NULL)
    )
`

type GetPermissionAssignmentParams struct {
	PrincipalType string
	PrincipalID   string
	Permission    string
	Effect        string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
}

func (q *Queries) GetPermissionAssignment(ctx context.Context, arg GetPermissionAssignmentParams) (PermissionAssignment, error) {
	row := q.db.QueryRowContext(ctx, getPermissionAssignment,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.Effect,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i PermissionAssignment
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.Effect,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupIDsForPrincipal = `-- name: ListGroupIDsForPrincipal :many
SELECT group_id
FROM group_memberships
WHERE principal_type = $1 AND principal_id = $2
`

type ListGroupIDsForPrincipalParams struct {
	PrincipalType string
	PrincipalID   string
}

func (q *Queries) ListGroupIDsForPrincipal(ctx context.Context, arg ListGroupIDsForPrincipalParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGroupIDsForPrincipal, arg.PrincipalType, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMemberships = `-- name: ListGroupMemberships :many
SELECT
    id,
    group_id,
    principal_type,
    principal_id,
    created_at,
    updated_at
FROM group_memberships
ORDER BY created_at
`

func (q *Queries) ListGroupMemberships(ctx context.Context) ([]GroupMembership, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMembership
	for rows.Next() {
		var i GroupMembership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
FROM groups
ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.IsProtected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingAssignmentsForPrincipal = `-- name: ListMatchingAssignmentsForPrincipal :many
SELECT
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
FROM permission_assignments
WHERE
    principal_type = $1
    AND principal_id = $2
    AND permission = $3
    AND (
        scope_type = $4
        OR (scope_type IS NULL AND $4 IS NULL)
    )
    AND (
        scope_id = $5
        OR (scope_id IS NULL AND $5 IS NULL)
    )
`

type ListMatchingAssignmentsForPrincipalParams struct {
	PrincipalType string
	PrincipalID   string
	Permission    string
	ScopeType     sql.NullString
	ScopeID       sql.NullString
}

func (q *Queries) ListMatchingAssignmentsForPrincipal(ctx context.Context, arg ListMatchingAssignmentsForPrincipalParams) ([]PermissionAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listMatchingAssignmentsForPrincipal,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.ScopeType,
		arg.ScopeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionAssignment
	for rows.Next() {
		var i PermissionAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.Effect,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionAssignments = `-- name: ListPermissionAssignments :many
SELECT
    id,
    principal_type,
    principal_id,
    permission,
    effect,
    scope_type,
    scope_id,
    created_at,
    updated_at
FROM permission_assignments
ORDER BY created_at
`

func (q *Queries) ListPermissionAssignments(ctx context.Context) ([]PermissionAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionAssignment
	for rows.Next() {
		var i PermissionAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.Effect,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET
    display_name = $1,
    is_protected = $2,
    updated_at = $3
WHERE id = $4
RETURNING
    id,
    name,
    display_name,
    is_protected,
    created_at,
    updated_at
`

type UpdateGroupParams struct {
	DisplayName string
	IsProtected bool
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.DisplayName,
		arg.IsProtected,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IsProtected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
