// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
    id,
    user_id,
    token_digest,
    user_agent,
    ip_address,
    expires_at,
    idle_expires_at,
    last_seen_at,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    user_id,
    token_digest,
    user_agent,
    ip_address,
    expires_at,
    idle_expires_at,
    revoked_at,
    last_seen_at,
    created_at,
    updated_at
`

type CreateUserSessionParams struct {
	ID            string
	UserID        string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.TokenDigest,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByTokenDigest = `-- name: GetUserSessionByTokenDigest :one
SELECT
    id,
    user_id,
    token_digest,
    user_agent,
    ip_address,
    expires_at,
    idle_expires_at,
    revoked_at,
    last_seen_at,
    created_at,
    updated_at
FROM user_sessions
WHERE token_digest = ?
`

func (q *Queries) GetUserSessionByTokenDigest(ctx context.Context, tokenDigest string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionByTokenDigest, tokenDigest)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionWithUser = `-- name: GetUserSessionWithUser :one
SELECT
    user_sessions.id,
    user_sessions.user_id,
    users.username,
    users.display_name,
    user_sessions.token_digest,
    user_sessions.user_agent,
    user_sessions.ip_address,
    user_sessions.expires_at,
    user_sessions.idle_expires_at,
    user_sessions.revoked_at,
    user_sessions.last_seen_at,
    user_sessions.created_at,
    user_sessions.updated_at
FROM user_sessions
JOIN users ON users.id = user_sessions.user_id
WHERE user_sessions.id = ?
`

type GetUserSessionWithUserRow struct {
	ID            string
	UserID        string
	Username      string
	DisplayName   string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	RevokedAt     sql.NullTime
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserSessionWithUser(ctx context.Context, id string) (GetUserSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionWithUser, id)
	var i GetUserSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.TokenDigest,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSessionsWithUsers = `-- name: ListUserSessionsWithUsers :many
SELECT
    user_sessions.id,
    user_sessions.user_id,
    users.username,
    users.display_name,
    user_sessions.token_digest,
    user_sessions.user_agent,
    user_sessions.ip_address,
    user_sessions.expires_at,
    user_sessions.idle_expires_at,
    user_sessions.revoked_at,
    user_sessions.last_seen_at,
    user_sessions.created_at,
    user_sessions.updated_at
FROM user_sessions
JOIN users ON users.id = user_sessions.user_id
ORDER BY user_sessions.created_at DESC
`

type ListUserSessionsWithUsersRow struct {
	ID            string
	UserID        string
	Username      string
	DisplayName   string
	TokenDigest   string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	RevokedAt     sql.NullTime
	LastSeenAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListUserSessionsWithUsers(ctx context.Context) ([]ListUserSessionsWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessionsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsWithUsersRow
	for rows.Next() {
		var i ListUserSessionsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.TokenDigest,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSession = `-- name: RevokeUserSession :one
UPDATE user_sessions
SET
    revoked_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    user_id,
    token_digest,
    user_agent,
    ip_address,
    expires_at,
    idle_expires_at,
    revoked_at,
    last_seen_at,
    created_at,
    updated_at
`

type RevokeUserSessionParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, revokeUserSession, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchUserSession = `-- name: TouchUserSession :one
UPDATE user_sessions
SET
    last_seen_at = ?,
    idle_expires_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING
    id,
    user_id,
    token_digest,
    user_agent,
    ip_address,
    expires_at,
    idle_expires_at,
    revoked_at,
    last_seen_at,
    created_at,
    updated_at
`

type TouchUserSessionParams struct {
	LastSeenAt    time.Time
	IdleExpiresAt time.Time
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) TouchUserSession(ctx context.Context, arg TouchUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, touchUserSession,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
