// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const getAppSecuritySettings = `-- name: GetAppSecuritySettings :one
SELECT
    id,
    force_peer_review_for_status_changes,
    session_idle_timeout_minutes,
    session_absolute_timeout_minutes,
    created_at,
    updated_at
FROM app_security_settings
WHERE id = ?
`

func (q *Queries) GetAppSecuritySettings(ctx context.Context, id string) (AppSecuritySetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSecuritySettings, id)
	var i AppSecuritySetting
	err := row.Scan(
		&i.ID,
		&i.ForcePeerReviewForStatusChanges,
		&i.SessionIdleTimeoutMinutes,
		&i.SessionAbsoluteTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
