// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createAppSecuritySettings = `-- name: CreateAppSecuritySettings :one
INSERT INTO app_security_settings (
    id,
    force_peer_review_for_status_changes,
    session_idle_timeout_minutes,
    session_absolute_timeout_minutes,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    force_peer_review_for_status_changes,
    session_idle_timeout_minutes,
    session_absolute_timeout_minutes,
    created_at,
    updated_at
`

type CreateAppSecuritySettingsParams struct {
	ID                              string
	ForcePeerReviewForStatusChanges bool
	SessionIdleTimeoutMinutes       sql.NullInt64
	SessionAbsoluteTimeoutMinutes   sql.NullInt64
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

func (q *Queries) CreateAppSecuritySettings(ctx context.Context, arg CreateAppSecuritySettingsParams) (AppSecuritySetting, error) {
	row := q.db.QueryRowContext(ctx, createAppSecuritySettings,
		arg.ID,
		arg.ForcePeerReviewForStatusChanges,
		arg.SessionIdleTimeoutMinutes,
		arg.SessionAbsoluteTimeoutMinutes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AppSecuritySetting
	err := row.Scan(
		&i.ID,
		&i.ForcePeerReviewForStatusChanges,
		&i.SessionIdleTimeoutMinutes,
		&i.SessionAbsoluteTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppSecuritySettings = `-- name: GetAppSecuritySettings :one
SELECT
    id,
    force_peer_review_for_status_changes,
    session_idle_timeout_minutes,
    session_absolute_timeout_minutes,
    created_at,
    updated_at
FROM app_security_settings
WHERE id = $1
`

func (q *Queries) GetAppSecuritySettings(ctx context.Context, id string) (AppSecuritySetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSecuritySettings, id)
	var i AppSecuritySetting
	err := row.Scan(
		&i.ID,
		&i.ForcePeerReviewForStatusChanges,
		&i.SessionIdleTimeoutMinutes,
		&i.SessionAbsoluteTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppSecuritySettings = `-- name: UpdateAppSecuritySettings :one
UPDATE app_security_settings
SET
    force_peer_review_for_status_changes = $1,
    session_idle_timeout_minutes = $2,
    session_absolute_timeout_minutes = $3,
    updated_at = $4
WHERE id = $5
RETURNING
    id,
    force_peer_review_for_status_changes,
    session_idle_timeout_minutes,
    session_absolute_timeout_minutes,
    created_at,
    updated_at
`

type UpdateAppSecuritySettingsParams struct {
	ForcePeerReviewForStatusChanges bool
	SessionIdleTimeoutMinutes       sql.NullInt64
	SessionAbsoluteTimeoutMinutes   sql.NullInt64
	UpdatedAt                       time.Time
	ID                              string
}

func (q *Queries) UpdateAppSecuritySettings(ctx context.Context, arg UpdateAppSecuritySettingsParams) (AppSecuritySetting, error) {
	row := q.db.QueryRowContext(ctx, updateAppSecuritySettings,
		arg.ForcePeerReviewForStatusChanges,
		arg.SessionIdleTimeoutMinutes,
		arg.SessionAbsoluteTimeoutMinutes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i AppSecuritySetting
	err := row.Scan(
		&i.ID,
		&i.ForcePeerReviewForStatusChanges,
		&i.SessionIdleTimeoutMinutes,
		&i.SessionAbsoluteTimeoutMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
