// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const getUser = `-- name: GetUser :one
SELECT
    id,
    username,
    display_name,
    is_active,
    created_at,
    updated_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordCredentialByUserID = `-- name: GetUserPasswordCredentialByUserID :one
SELECT
    id,
    user_id,
    password_hash,
    created_at,
    updated_at
FROM user_password_credentials
WHERE user_id = ?
`

func (q *Queries) GetUserPasswordCredentialByUserID(ctx context.Context, userID string) (UserPasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordCredentialByUserID, userID)
	var i UserPasswordCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordCredentialByUsername = `-- name: GetUserPasswordCredentialByUsername :one
SELECT
    users.id,
    users.username,
    users.display_name,
    users.is_active,
    users.created_at,
    users.updated_at,
    user_password_credentials.password_hash
FROM users
JOIN user_password_credentials ON user_password_credentials.user_id = users.id
WHERE users.username = ?
`

type GetUserPasswordCredentialByUsernameRow struct {
	ID           string
	Username     string
	DisplayName  string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetUserPasswordCredentialByUsername(ctx context.Context, username string) (GetUserPasswordCredentialByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordCredentialByUsername, username)
	var i GetUserPasswordCredentialByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPasswordCredential = `-- name: UpdateUserPasswordCredential :one
UPDATE user_password_credentials
SET
    password_hash = ?,
    updated_at = ?
WHERE user_id = ?
RETURNING
    id,
    user_id,
    password_hash,
    created_at,
    updated_at
`

type UpdateUserPasswordCredentialParams struct {
	PasswordHash string
	UpdatedAt    time.Time
	UserID       string
}

func (q *Queries) UpdateUserPasswordCredential(ctx context.Context, arg UpdateUserPasswordCredentialParams) (UserPasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasswordCredential, arg.PasswordHash, arg.UpdatedAt, arg.UserID)
	var i UserPasswordCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
